pythonweb/movieholic/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView, LogoutView

from .views import home, SignUpView

urlpatterns = [
    url(r'home$', home, name="movieholic_home"),
    url(r'login$',
        LoginView.as_view(template_name="movieholic/login_form.html"),
        name="movieholic_login"),
    url(r'logout$',
        LogoutView.as_view(),
        name="movieholic_logout"),
    url(r'signup$', SignUpView.as_view(), name='movieholic_signup'),
]

pythonweb/moviepoll/urls.py
from django.urls import path

from . import views

app_name = 'moviepoll'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

pythonweb/pythonweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

from .views import welcome


urlpatterns = [
    path('admin/', admin.site.urls),
    path('moviepoll/', include('moviepoll.urls'), name="moviepoll_home"),
    path('movieholic/', include('movieholic.urls')),
    url(r'^$', welcome, name="pythonweb_welcome")
]
urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

pythonweb/movieholic/models.py
from django.db import models

# Create your models here.

pythonweb/moviepoll/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    choice_img = models.ImageField(null=True, blank=True, upload_to="movie_images")
    choice_genre = models.CharField(null=True, max_length=200, blank=True)
    choice_imdb = models.FloatField(null=True, blank=True, default=False)
    choice_description = models.CharField(null=True, max_length=500, blank=True, default=False)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

pythonweb/movieholic/views.py
from django.shortcuts import render
from moviepoll.models import Question
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# Create your views here.
@login_required
def home(request):
    return render(request, "movieholic/home.html",
                    {'all_question': Question.objects.all()})

class SignUpView(CreateView):
    form_class = UserCreationForm
    template_name = "movieholic/signup_form.html"
    success_url = reverse_lazy('movieholic_home')

pythonweb/moviepoll/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth.decorators import login_required

from .models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'moviepoll/index.html'
    context_object_name = 'latest_question_list'
    
    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now())


class DetailView(generic.DetailView):
    model = Question
    template_name = 'moviepoll/detail.html'

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'moviepoll/results.html'

@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        return render(request, "moviepoll/detail.html", {
            "question": question,
            "error_message": "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('moviepoll:results', args=(question.id,)))

pythonweb/pythonweb/views.py
from django.shortcuts import render, redirect

def welcome(request):
    if request.user.is_authenticated:
        return redirect('movieholic_home')
    else:
        return render(request, 'pythonweb/welcome.html')

pythonweb/moviepoll/templates/moviepoll/detail.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'moviepoll/detail.css' %}">

<h2>{{ question.question_text }}</h2>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'moviepoll:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}

    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <div class="clearfix">
    {% if choice.choice_img %}
        <img class="img" src="{{ choice.choice_img.url }}" width="450" height="600"><br>
    {% endif %}    
    <h1><big><b>{{ choice.choice_text }}</big></b></h1>
    <h3><big><b>Genre:</b></big> <i>{{ choice.choice_genre }}</i></h3>
    <h3><big><b>IMDb:</b></big> {{ choice.choice_imdb }}</h3><br><br>
    <h4>{{ choice.choice_description }}</h4>
   
    </div>

   

{% endfor %}
<input type="submit" value="Vote">
</form>

pythonweb/moviepoll/templates/moviepoll/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'moviepoll/style.css' %}">

{% if latest_question_list %}
    <h5>WHAT WE HAVE SO FAR...</h5>
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'moviepoll:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</div>
{% if user.is_authenticated %}
    <h6><div class="topright"><a href="{% url 'movieholic_logout' %}">Logout</a></div></h6>
{% else %}
    <h6><div class="topright"><a href="{% url 'movieholic_login' %}">Login</a></div></h6>
{% endif %}

pythonweb/moviepoll/templates/moviepoll/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'moviepoll:detail' question.id %}">Vote again?</a>

pythonweb/templates/movieholic/home.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'movieholic/home.css' %}">



    <h1>Hi {{ user.username }}, these are the polls we have so far:</h1><br>
    <div class="transparent">
    {% for question in all_question%}
    <b><big><a href="{% url 'moviepoll:detail' question.id %}">{{ question.question_text }}</big></b></a><br>
    {% endfor %}
    </div>
    
    <h1>It's your turn to vote!</h1>
{% if user.is_authenticated %}
    <h6><div class="topright"><a href="{% url 'movieholic_logout' %}">Logout</a></div></h6>
{% else %}
    <h6><div class="topright"><a href="{% url 'movieholic_login' %}">Login</a></div></h6>
{% endif %}

pythonweb/templates/movieholic/login_form.html
{% load crispy_forms_tags %}



    <form role="form"
        action="{% url 'movieholic_login' %}"
        method="post">
        <p>Please prove that you are an Inteker.</p>
        {{ form | crispy}}
        {% csrf_token %} 
        <button type="submit" class="btn btn-success">Sign in</button>
        
        
    </form>
    

pythonweb/templates/movieholic/signup_form.html
{% load crispy_forms_tags %} 



    <form role="form"
        action="{% url 'movieholic_signup' %}"
        method="post">
        
        {% csrf_token %} 
        <p>An Inteker with no account? Fix it quickly!</p>
        
        {{ form|crispy }} 
        <button type="submit" class="btn btn-success">Sign up</button>
    </form> 

pythonweb/templates/pythonweb/welcome.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'pythonweb/style.css' %}">       


<div class="header">
  <h1>The Intek Movie Friday Night Poll</h1>
  

</div>
{% if user.is_authenticated %}
    <h6><div class="topright"><a href="{% url 'movieholic_logout' %}">Logout</a></div></h6>
{% else %}
    <h6><div class="topright"><a href="{% url 'movieholic_login' %}">Login</a></div></h6>
{% endif %}
    
<br><br><br><br><br><br><br>


<div class="transparent">


            <h2>Welcome movieholics in Intek!</h2>
            <h4>Pick the movie you wish to see.</h4>
</div>